fixed some issues with the workflow

diff --git a/.github/workflows/build_release.yaml b/.github/workflows/build_release.yaml
--- a/.github/workflows/build_release.yaml
+++ b/.github/workflows/build_release.yaml
@@ -1,12 +1,10 @@
 name: Build & Release
 
 # Run when a new version tag is pushed (v0.1.0 -> v0.1.1)
-on: 
+on:
     push:
         branches:
             - main
-        tags:
-            - 'v*.*.*'
     workflow_dispatch:
 
 jobs:
@@ -19,14 +17,16 @@ jobs:
               id: get_repo_name
               run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
 
-            # Step 0.2: Get Version from Tag
-            - name: Get Version from Tag
-              id: get_version
-              run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
-
             # Step 1: Checkout Repository
             - name: Checkout code
               uses: actions/checkout@v4
+
+            # Step 1.5: Get Version from pubspec.yaml
+            - name: Get Version from pubspec.yaml
+              id: get_version
+              run: |
+                  version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
+                  echo "VERSION=${{env.VERSION}}" >> $GITHUB_ENV
 
             # Step 2: Setup Flutter
             - name: Setup Flutter
@@ -38,8 +38,8 @@ jobs:
             - name: Setup Java
               uses: actions/setup-java@v3.12.0
               with:
-                distribution: 'oracle'
-                java-version: '17'
+                  distribution: 'oracle'
+                  java-version: '17'
 
             # Step 3: Verify Flutter
             - name: Verify Flutter
@@ -74,22 +74,22 @@ jobs:
             # Step 7: Rename APK and AAB Files
             - name: Rename APK and AAB Files
               run: |
-                  mv build/app/outputs/bundle/**/*.aab build/app/outputs/bundle/$REPO_NAME-$VERSION.aab
-                  mv build/app/outputs/flutter-apk/*.apk build/app/outputs/flutter-apk/$REPO_NAME-$VERSION.apk
+                  mv build/app/outputs/bundle/**/*.aab build/app/outputs/bundle/${{env.REPO_NAME}}-v${{env.VERSION}}.aab
+                  mv build/app/outputs/flutter-apk/*.apk build/app/outputs/flutter-apk/${{env.REPO_NAME}}-v${{env.VERSION}}.apk
 
             # Step 8.1: Upload AAB File
             - name: Upload AAB File
               uses: actions/upload-artifact@v4
               with:
-                  name: $REPO_NAME-$VERSION-aab
-                  path: build/app/outputs/bundle/$REPO_NAME-$VERSION.aab
+                  name: ${{env.REPO_NAME}}-v${{env.VERSION}}-aab
+                  path: build/app/outputs/bundle/${{env.REPO_NAME}}-v${{env.VERSION}}.aab
 
             # Step 8.2: Upload APK File
             - name: Upload APK File
               uses: actions/upload-artifact@v4
               with:
-                  name: $REPO_NAME-$VERSION-apk
-                  path: build/app/outputs/flutter-apk/$REPO_NAME-$VERSION.apk
+                  name: ${{env.REPO_NAME}}-v${{env.VERSION}}-apk
+                  path: build/app/outputs/flutter-apk/${{env.REPO_NAME}}-v${{env.VERSION}}.apk
 
     build-ios:
         name: Build iOS
@@ -100,14 +100,16 @@ jobs:
               id: get_repo_name
               run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
 
-            # Step 0.2: Get Version from Tag
-            - name: Get Version from Tag
-              id: get_version
-              run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
-
             # Step 1: Checkout Repository
             - name: Checkout code
               uses: actions/checkout@v4
+
+            # Step 1.5: Get Version from pubspec.yaml
+            - name: Get Version from pubspec.yaml
+              id: get_version
+              run: |
+                  version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
+                  echo "VERSION=${{env.VERSION}}" >> $GITHUB_ENV
 
             # Step 2: Setup Flutter
             - name: Setup Flutter
@@ -145,56 +147,97 @@ jobs:
             - name: Compress Archives and IPAs
               run: |
                   cd build
-                  tar -czf $REPO_NAME-$VERSION-ios.tar.gz ios
+                  tar -czf ${{env.REPO_NAME}}-v${{env.VERSION}}-ios.tar.gz ios
 
             # Step 8: Upload Archives and IPAs
             - name: Upload Archives and IPAs
               uses: actions/upload-artifact@v4
               with:
-                  name: $REPO_NAME-$VERSION-ios
-                  path: build/$REPO_NAME-$VERSION-ios.tar.gz
+                  name: ${{env.REPO_NAME}}-v${{env.VERSION}}-ios
+                  path: build/${{env.REPO_NAME}}-v${{env.VERSION}}-ios.tar.gz
 
     release:
         name: Release
         runs-on: ubuntu-latest
         needs: [build-android, build-ios]
-        if: startsWith(github.ref, 'refs/tags/')
         steps:
             # Step 0.1: Get Repository Name
             - name: Get Repository Name
               id: get_repo_name
               run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
 
-            # Step 0.2: Get Version from Tag
-            - name: Get Version from Tag
+            # Step 1: Checkout Repository
+            - name: Checkout code
+              uses: actions/checkout@v4
+
+            # Step 0.2: Get Version from pubspec.yaml
+            - name: Get Version from pubspec.yaml
               id: get_version
-              run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
+              run: |
+                  version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
+                  echo "VERSION=${{env.VERSION}}" >> $GITHUB_ENV
 
             # Step 1.1: Download AAB Artifact (Android)
             - name: Download AAB Artifact
               uses: actions/download-artifact@v4
               with:
-                  name: ${{ needs.build-android.outputs.REPO_NAME }}-${{ needs.build-android.outputs.VERSION }}-aab
+                  name: ${{ needs.build-android.outputs.REPO_NAME }}-v${{ needs.build-android.outputs.VERSION }}-aab
 
             # Step 1.2: Download APK Artifact (Android)
             - name: Download APK Artifact
               uses: actions/download-artifact@v4
               with:
-                  name: ${{ needs.build-android.outputs.REPO_NAME }}-${{ needs.build-android.outputs.VERSION }}-apk
+                  name: ${{ needs.build-android.outputs.REPO_NAME }}-v${{ needs.build-android.outputs.VERSION }}-apk
 
             # Step 1.3: Download Artifacts (iOS)
             - name: Download Artifacts (iOS)
               uses: actions/download-artifact@v4
               with:
-                  name: ${{ needs.build-ios.outputs.REPO_NAME }}-${{ needs.build-ios.outputs.VERSION }}-ios
-              
-            # Step 2: Create Release
+                  name: ${{ needs.build-ios.outputs.REPO_NAME }}-v${{ needs.build-ios.outputs.VERSION }}-ios
+
+            # Step 2: Check if Tag Exists
+            - name: Check if Tag Exists
+              id: check_tag
+              run: |
+                  if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
+                    echo "TAG_EXISTS=true" >> $GITHUB_ENV
+                  else
+                    echo "TAG_EXISTS=false" >> $GITHUB_ENV
+                  fi
+
+            # Step 3: Create Tag (if it doesn't exist)
+            - name: Create Tag
+              if: env.TAG_EXISTS == 'false'
+              run: git tag "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
+
+            # Step 4: Create Release
             - name: Create Release
+              if: env.TAG_EXISTS == 'false'
+              id: create_release
               uses: ncipollo/release-action@v1
               with:
-                artifacts: |
-                  ${{ needs.build-android.outputs.REPO_NAME }}-${{ needs.build-android.outputs.VERSION }}-aab
-                  ${{ needs.build-android.outputs.REPO_NAME }}-${{ needs.build-android.outputs.VERSION }}-apk
-                  ${{ needs.build-ios.outputs.REPO_NAME }}-${{ needs.build-ios.outputs.VERSION }}-ios
-                tag: v${{ env.VERSION }}
-                token: ${{ secrets.TOKEN }}
+                  artifacts: |
+                      ${{ needs.build-android.outputs.REPO_NAME }}-v${{ needs.build-android.outputs.VERSION }}-aab
+                      ${{ needs.build-android.outputs.REPO_NAME }}-v${{ needs.build-android.outputs.VERSION }}-apk
+                      ${{ needs.build-ios.outputs.REPO_NAME }}-v${{ needs.build-ios.outputs.VERSION }}-ios
+                  tag: v${{ env.VERSION }}
+                  token: ${{ secrets.TOKEN }}
+
+            # Step 4.5: Check if Release was Created
+            - name: Check Release Creation
+              if: env.TAG_EXISTS == 'false'
+              run: |
+                  if [ -z "${{ steps.create_release.outputs.upload_url }}" ]; then
+                    echo "Release creation failed."
+                    exit 1
+                  fi
+
+            # Step 5: Upload Release Notes
+            - name: Upload Release Notes
+              if: env.TAG_EXISTS == 'false'
+              uses: actions/upload-release-asset@v1
+              with:
+                  upload_url: ${{ steps.create_release.outputs.upload_url }}
+                  asset_path: CHANGELOG.md
+                  asset_name: CHANGELOG.md
+                  asset_content_type: text/markdown
